CREATE DATABASE SIGED
GO
USE SIGED
GO

CREATE TABLE ROL (
  ID_ROL INT PRIMARY KEY IDENTITY(1, 1),
  NOMBRE_ROL VARCHAR(50) NOT NULL
)
GO

CREATE TABLE DEPARTAMENTO (
  ID_DEPARTAMENTO INT PRIMARY KEY IDENTITY(1, 1),
  NOMBRE_DEPARTAMENTO VARCHAR(100) NOT NULL,
  SIGLAS NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE USUARIOS (
  ID_USUARIO INT PRIMARY KEY IDENTITY(1, 1),
  ID_ROL INT NOT NULL,
  ID_DEPARTAMENTO INT NOT NULL,
  NOMBRE_USUARIO VARCHAR(50) NOT NULL,
  CONTRASENA VARCHAR(255) NOT NULL,
  ACTIVO BIT NOT NULL DEFAULT (1)
)
GO

CREATE TABLE DOCENTE (
  ID_DOCENTE INT PRIMARY KEY IDENTITY(1, 1),
  ID_USUARIO INT NOT NULL,
  NOMBRE_DOCENTE VARCHAR(100) NOT NULL,
  APELLIDO_PATERNO_DOCENTE VARCHAR(100) NOT NULL,
  APELLIDO_MATERNO_DOCENTE VARCHAR(100) NOT NULL,
  RFC VARCHAR(13) UNIQUE NOT NULL,
  CURP VARCHAR(18) UNIQUE NOT NULL,
  CORREO VARCHAR(100) UNIQUE NOT NULL,
  TELEFONO_DOCENTE VARCHAR(15),
  ACTIVO BIT NOT NULL DEFAULT (1)
)
GO

CREATE TABLE ESTATUS_EXPEDIENTE (
  ID_ESTATUS_EXP INT PRIMARY KEY IDENTITY(1, 1),
  NOMBRE_ESTATUS VARCHAR(50) NOT NULL
)
GO

CREATE TABLE CONVOCATORIA (
  ID_CONVOCATORIA INT PRIMARY KEY IDENTITY(1, 1),
  NOMBRE_CONVOCATORIA VARCHAR(100) NOT NULL,
  ANIO INT NOT NULL,
  DESCRIPCION NVARCHAR(MAX),
  FECHA_INICIO DATETIME NOT NULL,
  FECHA_FIN DATETIME NOT NULL,
  ACTIVO BIT NOT NULL DEFAULT (1)
)
GO

CREATE TABLE EXPEDIENTE (
  ID_EXPEDIENTE INT PRIMARY KEY IDENTITY(1, 1),
  ID_DOCENTE INT NOT NULL,
  ID_CONVOCATORIA INT NOT NULL,
  FECHA_CREACION DATETIME NOT NULL DEFAULT (GETDATE()),
  FECHA_CIERRE DATETIME,
  ACTIVO BIT NOT NULL DEFAULT (1)
)
GO

CREATE TABLE ESTATUS_DOCUMENTO (
  ID_ESTATUS_DOCUMENTO INT PRIMARY KEY IDENTITY(1, 1),
  NOMBRE_ESTATUS VARCHAR(50) NOT NULL,
  DESCRIPCION NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE TIPO_DOCUMENTO (
  ID_TIPO_DOCUMENTO INT PRIMARY KEY IDENTITY(1, 1),
  CLAVE VARCHAR(50) NOT NULL,
  NOMBRE_TIPO VARCHAR(100) NOT NULL,
  DESCRIPCION NVARCHAR(255) NOT NULL,
  ID_DEPARTAMENTO INT NOT NULL
)
GO

CREATE TABLE DOCUMENTO (
  ID_DOCUMENTO INT PRIMARY KEY IDENTITY(1, 1),
  ID_EXPEDIENTE INT NOT NULL,
  ID_TIPO_DOCUMENTO INT NOT NULL,
  ID_ESTATUS_DOCUMENTO INT NOT NULL,
  ID_USUARIO_CREADOR INT NOT NULL,
  NOMBRE_ARCHIVO_ORIGINAL VARCHAR(100) NOT NULL,
  FOLIO_INTERNO VARCHAR(50) NOT NULL,
  FECHA_CARGA DATETIME NOT NULL DEFAULT (GETDATE()),
  OBSERVACIONES NVARCHAR(MAX),
  NOMBRE_DOCUMENTO VARCHAR(100) NOT NULL,
  RUTA_ARCHIVO VARCHAR(255) NOT NULL,
  FECHA_SUBIDA DATETIME NOT NULL DEFAULT (GETDATE()),
  ACTIVO BIT NOT NULL DEFAULT (1)
)
GO

CREATE TABLE VALIDACION_DOCUMENTO (
  ID_VALIDACION_DOCUMENTO INT PRIMARY KEY IDENTITY(1, 1),
  ID_DOCUMENTO INT NOT NULL,
  ID_USUARIO_VALIDADOR INT NOT NULL,
  FECHA_VALIDACION DATETIME NOT NULL DEFAULT (GETDATE()),
  OBSERVACIONES NVARCHAR(MAX),
  RESULTADO BIT NOT NULL
)
GO

CREATE TABLE HISTORIAL_EXPEDIENTE (
  ID_HISTORIAL INT PRIMARY KEY IDENTITY(1, 1),
  ID_EXPEDIENTE INT NOT NULL,
  ID_ESTATUS_EXP INT NOT NULL,
  ID_USUARIO INT NOT NULL,
  FECHA_CAMBIO DATETIME NOT NULL DEFAULT (GETDATE()),
  COMENTARIO NVARCHAR(MAX) NOT NULL
)
GO

CREATE TABLE TICKETS (
  ID_TICKET INT PRIMARY KEY IDENTITY(1, 1),
  ID_USUARIO INT NOT NULL,
  ID_DOCENTE_GENERADOR INT,
  ID_USUARIO_RESPONSABLE INT,
  TIPO_TICKET VARCHAR(50) NOT NULL,
  TITULO VARCHAR(150) NOT NULL,
  DESCRIPCION NVARCHAR(MAX),
  FECHA_CREACION DATETIME NOT NULL DEFAULT (GETDATE()),
  ESTATUS VARCHAR(30) NOT NULL DEFAULT 'Abierto',
  PRIORIDAD VARCHAR(20) NOT NULL DEFAULT 'Media',
  FECHA_CIERRE DATETIME
)
GO

ALTER TABLE USUARIOS ADD FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
GO

ALTER TABLE USUARIOS ADD FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
GO

ALTER TABLE DOCENTE ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
GO

ALTER TABLE EXPEDIENTE ADD FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE (ID_DOCENTE)
GO

ALTER TABLE EXPEDIENTE ADD FOREIGN KEY (ID_CONVOCATORIA) REFERENCES CONVOCATORIA (ID_CONVOCATORIA)
GO

ALTER TABLE TIPO_DOCUMENTO ADD FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
GO

ALTER TABLE DOCUMENTO ADD FOREIGN KEY (ID_EXPEDIENTE) REFERENCES EXPEDIENTE (ID_EXPEDIENTE)
GO

ALTER TABLE DOCUMENTO ADD FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO)
GO

ALTER TABLE DOCUMENTO ADD FOREIGN KEY (ID_ESTATUS_DOCUMENTO) REFERENCES ESTATUS_DOCUMENTO (ID_ESTATUS_DOCUMENTO)
GO

ALTER TABLE DOCUMENTO ADD FOREIGN KEY (ID_USUARIO_CREADOR) REFERENCES USUARIOS (ID_USUARIO)
GO

ALTER TABLE VALIDACION_DOCUMENTO ADD FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO (ID_DOCUMENTO)
GO

ALTER TABLE VALIDACION_DOCUMENTO ADD FOREIGN KEY (ID_USUARIO_VALIDADOR) REFERENCES USUARIOS (ID_USUARIO)
GO

ALTER TABLE HISTORIAL_EXPEDIENTE ADD FOREIGN KEY (ID_EXPEDIENTE) REFERENCES EXPEDIENTE (ID_EXPEDIENTE)
GO

ALTER TABLE HISTORIAL_EXPEDIENTE ADD FOREIGN KEY (ID_ESTATUS_EXP) REFERENCES ESTATUS_EXPEDIENTE (ID_ESTATUS_EXP)
GO

ALTER TABLE HISTORIAL_EXPEDIENTE ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
GO

ALTER TABLE TICKETS ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
GO

ALTER TABLE TICKETS ADD FOREIGN KEY (ID_DOCENTE_GENERADOR) REFERENCES DOCENTE (ID_DOCENTE)
GO

ALTER TABLE TICKETS ADD FOREIGN KEY (ID_USUARIO_RESPONSABLE) REFERENCES USUARIOS (ID_USUARIO)
GO
